before:
  hooks:
    - go mod tidy
    - go generate ./...

changelog:
  use: github-native
  sort: asc
  abbrev: 0
  filters:
    exclude:
      - "^docs:"
      - typo

builds:
  - goos:
      - linux
      # - windows
      # - darwin
    goarch:
      - amd64
      # - arm
      # - arm64

archives:
  - format: binary

nfpms:
  - id: go-hass-anything
    package_name: go-hass-anything
    file_name_template: "{{ .ConventionalFileName }}"
    vendor: org.github.joshuar
    homepage: https://github.com/joshuar/go-hass-anything
    maintainer: Joshua Rich <joshua.rich@gmail.com>
    description: |-
      Send anything to Home Assistant, through MQTT, powered by Go.
    license: MIT
    formats:
      - deb
      - rpm
      - archlinux
    bindir: /usr/bin
    release: "1"
    section: default
    priority: extra
    meta: false
    contents:
      - src: LICENSE
        dst: /usr/share/licenses/go-hass-anything/LICENSE
      - src: README.md
        dst: /usr/share/doc/go-hass-anything/README.md
      - src: init/systemd/go-hass-anything.service
        dst: /usr/lib/systemd/user/go-hass-anything.service
    rpm:
      compression: lzma
    deb:
      lintian_overrides:
        - changelog-file-missing-in-native-package
    archlinux:
      packager: GoReleaser <staff@goreleaser.com>
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
