// Code generated by "stringer -type=ButtonType -output button_entity_generated.go -linecomment"; DO NOT EDIT.

package hass

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ButtonTypeNone-0]
	_ = x[ButtonTypeIdentify-1]
	_ = x[ButtonTypeRestart-2]
	_ = x[ButtonTypeUpdate-3]
}

const _ButtonType_name = "identifyrestartupdate"

var _ButtonType_index = [...]uint8{0, 0, 8, 15, 21}

func (i ButtonType) String() string {
	if i < 0 || i >= ButtonType(len(_ButtonType_index)-1) {
		return "ButtonType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ButtonType_name[_ButtonType_index[i]:_ButtonType_index[i+1]]
}
