// Code generated by "stringer -type=EntityType -output entityTypeStrings.go -linecomment"; DO NOT EDIT.

package hass

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[Sensor-1]
	_ = x[BinarySensor-2]
	_ = x[Button-3]
	_ = x[Number-4]
	_ = x[Switch-5]
	_ = x[Text-6]
	_ = x[Camera-7]
	_ = x[Image-8]
}

const _EntityType_name = "unknownsensorbinary_sensorbuttonnumberswitchtextcameraimage"

var _EntityType_index = [...]uint8{0, 7, 13, 26, 32, 38, 44, 48, 54, 59}

func (i EntityType) String() string {
	if i < 0 || i >= EntityType(len(_EntityType_index)-1) {
		return "EntityType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EntityType_name[_EntityType_index[i]:_EntityType_index[i+1]]
}
