// Code generated by "stringer -type=NumberMode -output numberModeStrings.go -linecomment"; DO NOT EDIT.

package hass

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NumberAuto-0]
	_ = x[NumberBox-1]
	_ = x[NumberSlider-2]
}

const _NumberMode_name = "autoboxslider"

var _NumberMode_index = [...]uint8{0, 4, 7, 13}

func (i NumberMode) String() string {
	if i < 0 || i >= NumberMode(len(_NumberMode_index)-1) {
		return "NumberMode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _NumberMode_name[_NumberMode_index[i]:_NumberMode_index[i+1]]
}
