// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mqtt

import (
	"sync"
)

// Ensure, that AgentConfigMock does implement AgentConfig.
// If this is not the case, regenerate this file with moq.
var _ AgentConfig = &AgentConfigMock{}

// AgentConfigMock is a mock implementation of AgentConfig.
//
//	func TestSomethingThatUsesAgentConfig(t *testing.T) {
//
//		// make and configure a mocked AgentConfig
//		mockedAgentConfig := &AgentConfigMock{
//			GetConfigFunc: func(s string, ifaceVal interface{}) error {
//				panic("mock out the GetConfig method")
//			},
//		}
//
//		// use mockedAgentConfig in code that requires AgentConfig
//		// and then make assertions.
//
//	}
type AgentConfigMock struct {
	// GetConfigFunc mocks the GetConfig method.
	GetConfigFunc func(s string, ifaceVal interface{}) error

	// calls tracks calls to the methods.
	calls struct {
		// GetConfig holds details about calls to the GetConfig method.
		GetConfig []struct {
			// S is the s argument value.
			S string
			// IfaceVal is the ifaceVal argument value.
			IfaceVal interface{}
		}
	}
	lockGetConfig sync.RWMutex
}

// GetConfig calls GetConfigFunc.
func (mock *AgentConfigMock) GetConfig(s string, ifaceVal interface{}) error {
	if mock.GetConfigFunc == nil {
		panic("AgentConfigMock.GetConfigFunc: method is nil but AgentConfig.GetConfig was just called")
	}
	callInfo := struct {
		S        string
		IfaceVal interface{}
	}{
		S:        s,
		IfaceVal: ifaceVal,
	}
	mock.lockGetConfig.Lock()
	mock.calls.GetConfig = append(mock.calls.GetConfig, callInfo)
	mock.lockGetConfig.Unlock()
	return mock.GetConfigFunc(s, ifaceVal)
}

// GetConfigCalls gets all the calls that were made to GetConfig.
// Check the length with:
//
//	len(mockedAgentConfig.GetConfigCalls())
func (mock *AgentConfigMock) GetConfigCalls() []struct {
	S        string
	IfaceVal interface{}
} {
	var calls []struct {
		S        string
		IfaceVal interface{}
	}
	mock.lockGetConfig.RLock()
	calls = mock.calls.GetConfig
	mock.lockGetConfig.RUnlock()
	return calls
}
