services:
  devcontainer:
    env_file:
      - .env
    image: mcr.microsoft.com/devcontainers/base:ubuntu
    hostname: devcontainer
    volumes:
      - ..:/workspace:cached
      - /etc/localtime:/etc/localtime:ro,cached
    command: sleep infinity
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    user: vscode
  mosquitto:
    env_file:
      - .env
    image: docker.io/eclipse-mosquitto:$MOSQUITTO_VERSION
    hostname: mosquitto
    volumes:
      - ../deployments/mosquitto/config:/mosquitto/config:z
      - ../deployments/mosquitto/data:/mosquitto/data:z
      - ../deployments/mosquitto/log:/mosquitto/log:z
      - /etc/localtime:/etc/localtime:ro,cached
    ports:
      - 1883:1883
      - 8883:8883
    restart: on-failure
  home-assistant:
    env_file:
      - .env
    image: ghcr.io/home-assistant/home-assistant:$HA_VERSION
    hostname: home-assistant
    volumes:
      - ../deployments/home-assistant/config:/config:z
    ports:
      - 8123:8123
    restart: on-failure
