version: "3.8"
services:
  devcontainer:
    build: 
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
      - /etc/localtime:/etc/localtime:ro,cached
    command: sleep infinity
    network_mode: host
    user: vscode
  mosquitto:
    image: docker.io/eclipse-mosquitto:2.0.18
    volumes:
      - ../deployments/mosquitto/config:/mosquitto/config:cached
      - ../deployments/mosquitto/data:/mosquitto/data
      - ../deployments/mosquitto/log:/mosquitto/log
      - /etc/localtime:/etc/localtime:ro,cached
    ports:
      - 1883:1883
      - 8883:8883
    restart: on-failure
  home-assistant:
    image: ghcr.io/home-assistant/home-assistant:2024.5.4
    volumes:
      - ../deployments/home-assistant/config:/config
    ports:
      - 8123:8123
    environment:
      - "TZ=${TZ}"
    restart: on-failure
