services:
  devcontainer:
    build:
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      - /etc/localtime:/etc/localtime:ro,cached
    command: sleep infinity
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
    user: vscode

  mosquitto:
    image: docker.io/eclipse-mosquitto:2.0.18
    volumes:
      - ../deployments/mosquitto/config:/mosquitto/config:cached
      - ../deployments/mosquitto/data:/mosquitto/data
      - ../deployments/mosquitto/log:/mosquitto/log
      - /etc/localtime:/etc/localtime:ro,cached
    ports:
      - 1883:1883
      - 8883:8883
    restart: on-failure

  home-assistant:
    image: ghcr.io/home-assistant/home-assistant:2024.9.3
    volumes:
      - ../deployments/home-assistant/config:/config
    ports:
      - 8123:8123
    restart: on-failure
