name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release_please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release_please
        name: Run release please
        with:
          release-type: go
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v3
        if: ${{ steps.release_please.outputs.release_created }}
        with:
          fetch-depth: 0

      - name: Setup Go
        if: ${{ steps.release_please.outputs.release_created }}
        id: setup_go
        uses: actions/setup-go@v4

      - name: Install Go dependencies
        if: ${{ steps.release_please.outputs.release_created }}
        id: install_go_deps
        run: |
          go install github.com/matryer/moq@latest

      - name: Run Go Releaser
        uses: goreleaser/goreleaser-action@v4
        if: ${{ steps.release_please.outputs.release_created }}
        id: run_goreleaser
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}